//
// Generated by Bluespec Compiler (build 00185f79)
//
// On Thu Apr  8 10:49:42 IST 2021
//
//
// Ports:
// Name                         I/O  size props
// the_answer                     O    32
// RDY_the_answer                 O     1 const
// ans                            O    32
// RDY_ans                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// the_answer_x                   I    32
// the_answer_y                   I    32
// the_answer_z                   I    32
// ans_a                          I    32
// ans_b                          I    32
// ans_c                          I    32
//
// Combinational paths from inputs to outputs:
//   (the_answer_x, the_answer_y, the_answer_z) -> the_answer
//   (ans_a, ans_b, ans_c) -> ans
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkModuleDeepThought(CLK,
			   RST_N,

			   the_answer_x,
			   the_answer_y,
			   the_answer_z,
			   the_answer,
			   RDY_the_answer,

			   ans_a,
			   ans_b,
			   ans_c,
			   ans,
			   RDY_ans);
  input  CLK;
  input  RST_N;

  // value method the_answer
  input  [31 : 0] the_answer_x;
  input  [31 : 0] the_answer_y;
  input  [31 : 0] the_answer_z;
  output [31 : 0] the_answer;
  output RDY_the_answer;

  // value method ans
  input  [31 : 0] ans_a;
  input  [31 : 0] ans_b;
  input  [31 : 0] ans_c;
  output [31 : 0] ans;
  output RDY_ans;

  // signals for module outputs
  wire [31 : 0] ans, the_answer;
  wire RDY_ans, RDY_the_answer;

  // value method the_answer
  assign the_answer = the_answer_x + the_answer_y + the_answer_z ;
  assign RDY_the_answer = 1'd1 ;

  // value method ans
  assign ans = ans_a + ans_b - ans_c ;
  assign RDY_ans = 1'd1 ;
endmodule  // mkModuleDeepThought

